#!/bin/bash

# Build the container
docker build -t secp256k1-wasm .
# Run the container
docker run --name linux-build --entrypoint=sh -d -i secp256k1-wasm

# Copy the secp256k1 folder inside the container
docker cp ./secp256k1-zkp/. linux-build:/build/secp256k1-zkp
# Copy the C wrapper
docker cp ./src/main.c linux-build:/build
# Copy the custom build script inside the container
docker cp ./scripts/build_wasm linux-build:/build

# Compile to wasm target
docker exec linux-build bash build_wasm

# Copy the artifacts from the container to local directory
rm -rf src/lib/secp256k1-zkp.js
docker cp linux-build:/build/dist/secp256k1-zkp.js ./src/lib

docker kill linux-build
docker rm linux-build
#docker rmi secp256k1-wasm
